name: Frends.JSON.EnforceTypes Main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.JSON.EnforceTypes/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.JSON.EnforceTypes
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      